import keymirror from 'keymirror';

export default keymirror({
  SIGNUP_SUCCESSFUL: null,
  SIGNUP_UNSUCCESSFUL: null,
  SIGNUP_VALIDATION_ERROR: null,
  SIGNIN_SUCCESSFUL: null,
  SIGNIN_UNSUCCESSFUL: null,
  ADDBOOK_SUCCESSFUL: null,
  ADDBOOK_UNSUCCESSFUL: null,
  ADDBOOK_VALIDATION_ERROR: null,
  ADDCATEGORY_SUCCESSFUL: null,
  ADDCATEGORY_UNSUCCESSFUL: null,
  ADDCATEGORY_VALIDATION_ERROR: null,
  GETCATEGORY_SUCCESSFUL: null,
  GETCATEGORY_UNSUCCESSFUL: null,
  GETBOOKS_SUCCESSFUL: null,
  GETBOOKS_UNSUCCESSFUL: null,
  GETUSERS_SUCCESSFUL: null,
  GETUSERS_UNSUCCESSFUL: null,
  INVALID_TOKEN: null,
  UNAUTHORIZED_TOKEN: null
});